export default {
  RESTORE_FROM_LOCAL_STORAGE: "RESTORE_FROM_LOCAL_STORAGE",
  INITIALIZE_STATE: "INITIALIZE_STATE",
  SAVE_TO_LOCAL_STORAGE: "SAVE_TO_LOCAL_STORAGE",
  ADD_TOKEN: "ADD_TOKEN",
  ADD_TEAM: "ADD_TEAM",
  REMOVE_TEAM: "REMOVE_TEAM",
  ADD_CHANNEL: "ADD_CHANNEL",
  REMOVE_CHANNEL: "REMOVE_CHANNEL",
  SET_TEAM_INFO: "SET_TEAM_INFO",
}
